/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 BaseHuman.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/BaseHuman.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.root} />
      <skinnedMesh geometry={nodes.human_male001_1.geometry} material={materials['cornea.001']} skeleton={nodes.human_male001_1.skeleton} />
      <skinnedMesh geometry={nodes.human_male001_2.geometry} material={materials['cornea.001']} skeleton={nodes.human_male001_2.skeleton} />
      <skinnedMesh geometry={nodes.human_male001_3.geometry} material={materials['cornea.001']} skeleton={nodes.human_male001_3.skeleton} />
      <skinnedMesh geometry={nodes.human_male001_4.geometry} material={materials['cornea.001']} skeleton={nodes.human_male001_4.skeleton} />
      <lineSegments geometry={nodes.meshes0.geometry} material={materials['human_skin.001']} />
      <skinnedMesh geometry={nodes.meshes0_1.geometry} material={materials['human_skin.001']} skeleton={nodes.meshes0_1.skeleton} />
    </group>
  )
}

useGLTF.preload('/BaseHuman.gltf')
